workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
  GIT_STRATEGY: clone

default:
  cache:
    key:
      files:
        - blockrules.txt
        - noise.txt
    paths:
      - _public/

run:
  stage: build
  image: node:latest
  script:
    - npm i -g @adguard/hostlist-compiler
    # - npm audit fix --force
    - hostlist-compiler -c tools/hostscompilerconf.json
      -o _public/blockrules.txt

pages:
  stage: deploy
  image: alpine:latest
  variables:
    GIT_STRATEGY: clone
  script:
    # - apk add rsync
    # - rm -rf public
    # - mkdir public
    # - rsync -avP _public/ public/
    - mv _public public
    - cp rules/noise.txt public/noise.txt
    - ls -lha public/
    - head -n 15 public/blockrules.txt
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
