# The Docker image that will be used to build your app
image: ubuntu:22.04

variables:
  PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'

before_script:
  - echo "Before script section"
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -yqqf bash git pgp python3-pip python3.10 rsync
  - git config --global user.email "spirillen@danwin1210.de"
  - git config --global user.name "spirillen"
  - git remote set-url origin https://spirillen:$mypdns_CI_ACCESS_TOKEN@framagit.org/$CI_PROJECT_PATH.git
  #   - python --version  # For debugging
  - if [ -f requirements.txt ]; then python3.10 -m pip install --no-cache -I -r requirements.txt; fi

after_script:
  - echo -e "After script section...\n"
  - git pull --rebase
  - git status
  - git rev-parse --short HEAD > .build.id
  - git add _public/blockrules.txt .build.id
  - git commit -m "AdBlocker list updated. BuildID $CI_JOB_ID [ci-skip]"
  - git push "https://spirillen:${mypdns_CI_ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_REF_NAME}" -o skip-ci
  - git status

run:
  stage: build
  script:
    - if [ -f _public/blockrules.txt ]; then rm -f _public/blockrules.txt; fi
    - flrender -v -i ublockorigin-rules=. adblocker-rules.template _public/blockrules.txt

pages:
  stage: deploy
  variables:
    FF_USE_FASTZIP: 'true'
    ARTIFACT_COMPRESSION_LEVEL: 'slowest'
    CACHE_COMPRESSION_LEVEL: 'fastest'
  script:
    - mkdir .public
    - rsync -avP _public/* .public/
    - rm -rf public
    - mv .public public
    # - wget -O public/blockrules.txt "https://framagit.org/my-privacy-dns/adblocker-rules/-/raw/master/_public/blockrules.txt"
    - ls -lha public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
