image: ubuntu:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - echo "Before script section"
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -yqqf bash git pgp python3-pip
  - git config --global user.email "pdns@pm.me"
  - git config --global user.name "My Privacy DNS"
  - git remote set-url origin https://mypdns:$mypdns_CI_ACCESS_TOKEN@mypdns.org/$CI_PROJECT_PATH.git
  - python --version  # For debugging
  - if [ -f requirements.txt ]; then pip install --no-cache -I -r requirements.txt; fi

after_script:
  - echo -e "After script section...\n"
  - git status
  - git add _public/blockrules.txt
  - git commit -m "AdBlocker list updated. BuildID $CI_JOB_ID"
  - git status
  - git push "https://mypdns:${MYPDNS_CI_ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_REF_NAME}" -o skip-ci
  - ls -lha && ls -lha _public/

run:
  stage: build
  script:
    flrender -v -i ublockorigin-rules=. ublockorigin-rules.template _public/blockrules.txt

# pages:
#   stage: deploy
#   script:
#     - mkdir .public
#     - cp -r _public/ .public/
#     - rm -rf public
#     - mv .public public
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
