image: python:latest

before_script:
  - python3 -m pip install --no-cache-dir --upgrade git+https://github.com/adblockplus/python-abp
  - git config --global user.name "${GITLAB_USER_NAME}"
  - git config --global user.email "${GITLAB_USER_EMAIL}"

pages:
  stage: deploy
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - ./update-3rdparties.sh
    - flrender -i ublockorigin-rules=. AnonymousPoster.template public/blockrules.txt
    #- flrender --help
    #- url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git remote set-url origin "https://gitlab-ci-token:${DEPLOY_KEY}@${url_host}"
    - git add .
    - git commit -m '[skip ci] commit from CI runner'
    - git push "https://${GITLAB_USER_NAME}:${DEPLOY_KEY}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_REF_NAME}"
  artifacts:
    paths:
    - public
  only:
    - master
