# The Docker image that will be used to build your app
image: ubuntu:latest

variables:
  PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
  GIT_STRATEGY: clone

before_script:
  - echo "Before script section"
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -yqqf bash git pgp python3-pip python3.10 rsync npm
  - git config --global user.email "spirillen@danwin1210.de"
  - git config --global user.name "spirillen"
  - git remote set-url origin https://spirillen:$CI_ACCESS_TOKEN@0xacab.org/$CI_PROJECT_PATH.git
  #   - python --version  # For debugging
  - if [ -f requirements.txt ]; then python3.10 -m pip install --no-cache -I -r requirements.txt; fi

after_script:
  - echo -e "After script section...\n"
  - git status
  - git add _public/blockrules.txt
  - git commit -m "AdBlocker list updated. BuildID $CI_JOB_ID [ci-skip]"
  - git pull --rebase
  - git push origin master "https://spirillen:${CI_ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_REF_NAME}" -o skip-ci
  - git status

run:
  stage: build
  allow_failure: false
  script:
    # - flrender -v -i ublockorigin-rules=. adblocker-rules.template _public/blockrules.txt
    # - sh flrender.sh
    - sh tools/hostlistcompiler.sh
    # - git add _public/blockrules.txt
    # - git commit -m "AdBlocker list updated. BuildID $BUILD"
    # - git pull --rebase
    # - git push "https://spirillen:${CI_ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_COMMIT_REF_NAME}" -o skip-ci

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
    - mkdir .public
    - rsync -avP _public/* .public/
    - rm -rf public
    - mv .public public
    - ls -lha public/
    - head -n 15 public/blockrules.txt
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
