name: Launch a new test
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  GIT_NAME: "${{ github.actor }}"
  GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  BuildRules:
    name: Trigger action
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9.1"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 3

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Render the rules
        run: |
          flrender -i ublockorigin-rules=. ublockorigin-rules.template _public/blockrules.txt

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          allow_empty_commit: true
          force_orphan: true

      # - name: Commit changes
      #   run: |
      #     git config --local user.email "$GIT_EMAIL"
      #     git config --local user.name "$GIT_NAME"
      #     git commit -m "Release $(git --git-dir ../.git rev-parse --short HEAD)" -a

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
