blank_issues_enabled: false
contact_links:
  - name: My Privacy DNS Community Support
    url: https://mypdns.org/my-external-stuff/ublockorigin-rules/-/issues
    about: Please ask and answer questions here.
