blank_issues_enabled: false
contact_links:
  - name: My Privacy DNS Community Support
    url: https://spirillen.atlassian.net/jira/software/c/projects/UBOR/issues
    about: Please ask and answer questions here.
