name: Deploy new rules
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: '01 * * * *'

env:
  GIT_NAME: "${{ secrets.GIT_NAME }}"
  GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  buildrules:
    name: Trigger action
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9.5"
        os:
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 5

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Render the rules
        run: |
          flrender -v -i ublockorigin-rules=. ublockorigin-rules.template _public/blockrules.txt
          python FOP.py _public/blockrules.txt

      - name: Deploy
        run: |
          cd _public
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Release $(git --git-dir ../.git rev-parse --short HEAD)"

      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: _public
